const NwfUsers = {
    "zachary": {
        "id": "zachary",
        "discord": "zachary.bachary",
        "discordid": "804839006403428423",
        "gamename": "ZacharyBachary",
        "awards": [
            "eurasiaModern_winner",
            "hre_winner",
			"owbcaribean_winner",
			"feudalismac_winner",
			"world1861_winner",
			"eurasia6coalition_winner",
			"worldww2_winner",
			"eurasia5_winner",
			"mars_winner",
			"usa_winner",
			"eurasia2_winner",
			"tigerland_winner",
			"eurasia1_winner",
			"crimeanwar_super",
			"euammodern_global",
			"eurasiaww2_global",
			"worldkaiserreichp2_global",
			"euammodern_global",
			"ussr_global",
			"tigerlandnew_global",
			"usanew_global",
			"paraguayanwar_global",
			"euro4modern_global",
			"eurasia3_global",
			"historicalww1_global",
			"africa_global",
			"middleeast_global",
			"ww2og_global",
        ],
        "events": [
		    "worldNapoleon",
			"eurasiaModern",
            "hre",
			"owbcaribean",
			"feudalismac",
			"world1861",
			"eurasia6coalition",
			"worldww2",
			"eurasia5",
			"mars",
			"usa",
			"eurasia2",
			"tigerland",
			"eurasia1",
			"crimeanwar",
			"euammodern",
			"eurasiaww2",
			"worldkaiserreichp2",
			"euammodern",
			"ussr",
			"tigerlandnew",
			"usanew",
			"paraguayanwar",
			"euro4modern",
			"eurasia3",
			"historicalww1",
			"africa",
			"middleeast",
			"ww2og",
		],
    },
	"inka": {
		"id": "inka",
		"discord": "plagers1",
		"discordid": "1050563653394505728",
		"gamename": "Plagers",
		"awards": [
		    "tigerlandnew_global",
			"eurasia3_global",
			"eurasia3_global",
			"eurasia1_global",
			"owbcaribean_great",
			"feudalismac_great",
			"eurasiaww2_great",
			"eurasia6coalition_great",
			"ussr_great",
			"worldww2_great",
			"paraguayanwar_great",
			"hre_former",
		],
		"events": [
		    "worldNapoleon",
			"tigerlandnew",
			"eurasia3",
			"eurasia3",
			"eurasia1",
			"owbcaribean",
			"feudalismac",
			"eurasiaww2",
			"eurasia6coalition",
			"ussr",
			"worldww2",
			"paraguayanwar",
			"hre",
		],
	},
	"napoleon": {
		"id": "napoleon",
		"discord": "napoleon0544",
		"discordid": "1192203917757517825",
		"gamename": "Napoleon",
		"awards": [
		    "hre_global",
			"owbcaribean_global",
			"crimeanwar_former",
		],
		"events": [
		    "hre",
			"owbcaribean",
			"crimeanwar",
		],
	},
	"publicnuisance": {
	    "id": "publicnuisance",
		"discord": "stewardconstruct.",
		"discordid": "1114590604668706927",
		"gamename": "Public Nuisance",
		"awards": [
		    "euoemodern_great",
		],
		"events": [
		    "euomodern",
			"worldNapoleon",
		],
	},
	"mrgoxlem": {
	    "id": "mrgoxlem",
		"discord": "self_presev",
		"discordid": "1223823017004634206",
		"gamename": "Mrgoxlem",
		"awards": [
		    "feudalismac_global",
			"eurasiaModern_former",
		],
		"events": [
		    "feudalismac",
			"eurasiaModern",
		],
	},
	"useless": {
	    "id": "useless",
		"discord": "useless_yo",
		"discordid": "1111413830443081728",
		"gamename": "Useless",
		"awards": [
		    "eurasia6coalition_great",
		],
		"events": [
		    "eurasia6coalition",
		],
	},
	"eenot": {
		"id": "eenot",
		"discord": "enot_enot",
		"discordid": "794675642037567498",
		"gamename": "EEnot",
		"awards": [
		    "eurasiaModern_super",
			"euammodern_great",
		],
		"events": [
		    "eurasiaModern",
			"euammodern",
		],
	},
	"totoska": {
		"id": "totoska",
		"discord": "Totoska",
		"discordid": "820194328201920524",
		"gamename": "Totoska",
		"awards": [
		    "euoemodern_winner",
			"eurasiaww2_winner",
			"worldkaiserreichp2_winner",
			"euammodern_winner",
			"usanew_winner",
			"euro4modern_winner",
			"hre_super",
			"crimeanwar_super",
			"feudalismac_global",
			"world1861_global",
			"eurasia6coalition_global",
			"owbcaribean_great",
			"eurasia2_great",
		],
		"events": [
		    "euoemodern",
			"eurasiaww2",
			"worldkaiserreichp2",
			"euammodern",
			"usanew",
			"euro4modern",
			"hre",
			"crimeanwar",
			"feudalismac",
			"world1861",
			"eurasia6coalition",
			"owbcaribean",
			"eurasia2",
		],
	},
	"ottomanism": {
		"id": "ottomanism",
		"discord": "Ottomanism",
		"discordid": "1283840564839579701",
		"gamename": "Ottomanism",
		"awards": [
		    "crimeanwar_winner",
			"eurasiaModern_super",
			"hre_global",
			"owbcaribean_global",
			"world1861_global",
			"eurasiaww2_global",
			"worldkaiserreichp2_global",
			"euammodern_global",
			"feudalismac_great",
		],
		"events": [
		    "crimeanwar",
			"eurasiaModern",
			"hre",
			"owbcaribean",
			"world1861",
			"eurasiaww2",
			"worldkaiserreichp2",
			"euammodern",
			"feudalismac",
		],
	},
	"eggnog": {
		"id": "id",
		"discord": "Eggnog",
		"discordid": "1306064701037215828",
		"gamename": "Eggnog",
		"awards": [
		    "mars_global",
			"hre_great",
			"owbcaribean_great",
			"eurasiaModern_former",
			"crimeanwar_former",
		],
		"events": [
		    "ussr",
			"euro4modern",
			"mars",
			"mc",
			"euoemodern",
			"amnewciv",
			"feudalismac",
			"owbcaribean",
			"crimeanwar",
			"hre",
			"eurasiaModern",
			"deadhand",
			"worldNapoleon",
		],
	},
	"honse": {
		"id": "honse",
		"discord": "Honse",
		"discordid": "938218628170522694",
		"gamename": "Honse",
		"awards": [
		    "eurasiaModern_global",
			"crimeanwar_great",
		],
		"events": [
		    "crimeanwar",
			"hre",
			"eurasiaModern",
			"worldNapoleon",
		],
	},
	"graycar": {
		"id": "graycar",
		"discord": "gray-car",
		"discordid": "1260611002240860202",
		"gamename": "Gray car",
		"awards": [],
		"events": [
		    "hre",
			"eurasiaModern",
			"worldNapoleon",
		],
	},
	"moad": {
		"id": "moad",
		"discord": "Moad",
		"discordid": "846351504730619925",
		"gamename": "Moad",
		"awards": [
		    "ww1standard_winner",
			"worldww2_winner",
			"paraguayanwar_winner",
			"usa_winner",
			"middleeast_winner",
			"euoemodern_global",
			"world_1861_global",
			"eurasia5_global",
			"eurasia3_global",
			"ww2og_global",
			"eurasiaModern_great",
			"owbcaribean_great",
			"feudalismac_great",
			"worldkaiserreichp2_great",
			"hre_former",
			"crimeanwar_former",
			"feudalismac_former",
		],
	},
	"pepper": {
		"id": "pepper",
		"discord": "King Pepper",
		"discordid": "1262574507156045845",
		"gamename": "Mrpepper",
		"awards": [
		    "worldkaiserreichp2_great",
			"euammodern_great",
		],
		"events": [
		    "worldww2",
			"riseofislam",
			"tigerlandnew",
			"springofnations",
			"eurasia6coalition",
			"ww1standard",
			"worldkaiserreich",
			"world_coldwar",
			"novuscivilwar",
			"ottoman_win_ww1",
			"euammodern",
			"deadhand",
			"worldNapoleon",
		],
	},
	"psycho": {
		"id": "psycho",
		"discord": "PsychoPomp",
		"discordid": "1314822053488230501",
		"gamename": "psychopomp",
		"awards": [],
		"events": [
		    "deadhand",
			"worldNapoleon",
			"euammodern",
		],
	},
	"castoktz": {
		"id": "castoktz",
		"discord": "Castoktz",
		"discordid": "1249092055972577321",
		"gamename": "Castoktz",
		"awards": [
		    "tigerland_great",
			"historicalww1_great",
		],
		"events": [
		    "middleeast",
			"eurasia1",
			"talonia",
			"usa",
			"historicalww1",
			"tigerlandnew",
			"eurasia2",
			"eurasia3",
			"eurasia4",
			"owb",
			"ussr",
			"euro4modern",
			"constantinople",
			"WW2",
			"worldNapoleon",
		],
	},
	"sjosten": {
		"id": "sjosten",
		"discord": "Sjosten",
		"discordid": "1190382734087041175",
		"gamename": "Sjosten",
		"awards": [],
		"events": [
		    "usa",
			"eurasia3",
			"eurasia4",
			"owb",
			"lanperna",
			"euro4modern",
			"constantinople",
			"springofnations",
			"eurasiaww2",
			"euammodern",
		],
	},
	"purple": {
		"id": "purple",
		"discord": "Purple",
		"discordid": "866944111570583562",
		"gamename": "Purple Magnet",
		"awards": [
		    "euro4modern",
		],
		"events": [
		    "lanperna",
			"ussr",
			"euro4modern",
			"mars",
			"eurasia5",
			"ah",
			"paraguayanwar",
			"constantinople",
			"worldww2",
			"tigerlandnew",
			"ww1standard",
			"world_coldwar",
			"euammodern",
			"worldkaiserreichp2",
			"WW2",
			"og",
		],
	},
	"sinwrld": {
		"id": "sinwrld",
		"discord": "Sinwrld",
		"discordid": "1285740433485467719",
		"gamename": "Sinwrld",
		"awards": [
		    "world1861_great",
		],
		"events": [
		    "world1861",
			"euoemodern",
			"novuscivilwar",
			"feudalismac",
			"owbcaribean",
			"crimeanwar",
			"eurasiaModern",
			"deadhand",
		],
	},
	"aya": {
		"id": "aya",
		"discord": "AyaTwoLag®アヤツーラグ",
		"discordid": "1396439887170764852",
		"gamename": "AyaTwoLag",
		"awards": [],
		"events": [
		    "riseofottomans",
			"eurasiaww2",
			"deadhand",
		],
	},
	"beary": {
		"id": "beary",
		"discord": "beary",
		"discordid": "946239577096597504",
		"gamename": "beary",
		"awards": [
		    "eurasiaModern_great",
		],
		"events": [
		    "eurasiaModern",
			"deadhand",
		],
	},
	"manstein": {
		"id": "manstein",
		"discord": "Manstein",
		"discordid": "1098662845647945808",
		"gamename": "Manstein",
		"awards": [
		    "paraguayanwar_great",
		],
		"events": [
		    "eurasia5",
			"paraguayanwar",
			"constantinople",
			"usanew",
			"rome",
			"worldww2",
			"eurasia_6coalition",
			"ww1standard",
			"worldkaiserreich",
			"world_coldwar",
			"novuscivilwar",
			"ottoman_win_ww1",
			"WW2",
			"mc",
			"euoemodern",
			"novuscivilwar",
			"feudalismac",
			"eurasiaModern",
		]
	}
};

const NwfTypes = {
    "winner": {
        score: 15,
        name: "Winner of Event! "
    },
    "super": {
        score: 10,
        name: "Super Power! "
    },
    "global": {
        score: 5,
        name: "Global Power, "
    },
    "great": {
        score: 3,
        name: "Great Power, "
    },
    "former": {
        score: 3,
        name: "Honorary Former Power, "
    },
};

const NwfEvents = {
    worldww2: {
        name: 'WW2: World Map',
        date: '12.04.2025',
        map: 'zachary_world_v1_ww2',
    },
    ussr: {
        name: 'USSR',
        date: '03.05.2025',
        img: 'ussr.png',
    },
    eurasia6coalition: {
        name: 'Sixth Coalition',
        date: '04.05.2025',
        img: 'eurasia_6coalition.png',
    },
    euammodern: {
        name: 'Modern day North American and Europe',
        date: '15.06.2025',
        map: 'pelo_euam_v1_modern-en',
    },
    worldkaiserreichp2: {
        name: 'Kaiserreich Part 2',
        date: '28.06.2025',
        img: 'world_kaiserreich_p2.png',
    },
    eurasiaww2: {
        name: 'Eurasia WW2',
        date: '09.08.2025',
        map: 'zachary_eurasia_v2_1939',
    },
    world1861: {
        name: '1861 World Map',
        date: '23.08.2025',
        img: 'world_1861.png',
    },
    euoemodern: {
        name: 'Europe our Empire Modern',
        date: '06.09.2025',
        img: 'euoe_modern.png',
    },
    feudalismac: {
        name: 'Feudalism and Chivalry',
        date: '20.09.2025',
        img: 'euro4_1100s.png',
    },
    owbcaribean: {
        name: 'Old World Bones Carribean',
        date: '21.09.2025',
        img: 'owb_carribean.png',
    },
    crimeanwar: {
        name: 'Crimean War',
        date: '27.09.2025',
        img: 'euro4_crimeanwar.png',
    },
    hre: {
        name: 'Holy Roman Empire 1944',
        date: '28.09.2025',
        img: 'hre_1944.png',
    },
    eurasiaModern: {
        name: 'Eurasia Modern Day',
        date: '04.10.2025',
        map: 'zachary_eurasia_v2_modern',
    },
    worldNapoleon: {
        name: 'Napoleonic World',
        date: '12.10.2025',
        img: 'world_napoleon.png',
        //map: 'zahcary_world_v1_napoleon',
    },
	og: {
		name: 'Warnament Multiplayer Event',
		date: '26.10.2024',
		img: 'og.png',
	},
	ww2og: {
		name: 'WW2',
		date: '27.10.2024',
		img: 'ww2_og.png',
	},
	africa: {
		name: 'Africa',
		date: '02.11.2024',
		img: 'africa.jpg',
	},
	middleeast: {
		name: 'Middle East',
		date: '09.11.2024',
		img: 'middleeast.png',
	},
	eurasia1: {
		name: 'Eurasia: Part 1',
		date: '23.11.2024',
		img: 'eurasia1.png',
	},
	historicalww2: {
		name: 'World War II Historical',
		date: '24.11.2024',
		img: 'historicalww2.png'
	},
	historicalww1: {
		name: 'Historical WW1 Standarn EU',
		date: '07.12.2024',
		img: 'historicalww1.png',
	},
	tigerland: {
		name: 'Tigerland Civil War',
		date: '08.12.2024',
		map: 'chuckcha_tigerland_v3_civilwar-jalhund-en',
	},
	talonia: {
		name: 'Talonia World Map',
		date: '14.12.2024',
		img: 'talonia.png',
	},
	eurasia2: {
		name: 'Eurasia: Part 2',
		date: '21.12.2024',
		map: 'zachary_eurasia_v2_ep2',
	},
	eurasia3: {
		name: 'Eurasia: Part 3',
		date: '04.01.2025',
		map: 'zachary_eurasia_v2_ep3',
	},
	usa: {
		name: 'United States',
		date: '05.01.2025',
		map: 'zachary_usa_v1_2025',
	},
    eurasia4: {
		name: 'Eurasia: Part 4',
		date: '12.01.2025',
		map: 'zachary_eurasia_v2_ep4',
	},
	owb: {
		name: 'Old World Blues',
		date: '11.01.2025',
		img: 'owb.png',
	},
	euro4modern: {
		name: 'Euro4 Modern Day',
		date: '19.01.2025',
		img: 'euro4modern.png',
	},
	lanperna: {
		name: 'Lanperna',
		date: '18.01.2025',
		img: 'lanperna.png'
	},
	mars: {
		name: 'Terraformed Mars',
		date: '25.01.2025',
		img: 'mars.png'
	},
	ah: {
		name: 'Austria Hungary',
		date: '01.03.2025',
		img: 'ah.png',
	},
	paraguayanwar: {
		name: 'Paraguayan War',
		date: '08.03.2025',
		img: 'paraguayanwar.png',
	},
	constantinople: {
		name: 'Fall of Constantinople',
		date: '06.04.2025',
		img: 'constantinople.png',
	},
	rome: {
		name: 'Collapse of Rome',
		date: '30.03.2025',
		img: 'rome.png',
	},
	eurasia5: {
		name: 'Eurasia: Part 5',
		date: '05.04.2025',
		img: 'eurasia5.png',
	},
	worldww2: {
		name: 'World WW2',
		date: '12.04.2025',
		img: 'worldww2.png',
	},
	riseofislam: {
		name: 'Rise of Islam',
		date: '13.04.2025',
		img: 'riseofislam.png',
	},
	springofnations: {
		name: 'Spring of Nations',
		date: '19.04.2025',
		img: 'springofnations.png',
	},
	world1492: {
		name: 'World 1492',
		date: '26.04.2025',
		img: 'world1492.png',
	},
	ww1standard: {
		name: 'Standard WW1',
		date: '10.05.2025',
		img: 'ww1standard.png',
	},
	worldkaiserreich: {
		name: 'Kaiserreich',
		date: '11.05.2025',
		img: 'worldkaiserreich.png',
	},
	rpeuammodern: {
		name: "Full RP EU-NA Modern",
		date: '18.10.2025',
		map: 'pelo_euam_v2_modern-en',
	},
	usa_civilwar: {
		name: 'American Civil War',
		date: '24.05.2025',
		map: 'usa_civilwar.png',
	},
	world_coldwar: {
		name: 'Cold War',
		date: '01.06.2025',
		map: 'world_coldwar.png',
	},
	ottoman_win_ww1: {
		name: 'Ottomans Win WW1',
		date: '07.06.2025',
		map: 'ottoman_win_ww1.png',
	},
	worldwarnaminecraft: {
		name: 'Warnament Minecraft',
		date: '30.08.2025',
		map: 'worldwarnaminecraft.png',
	},
	riseofottomans: {
		name: 'Rise of the Ottomans',
		date: '16.08.2025',
		map: 'riseofottomans.png',
	},
	novuscivilwar: {
		name: 'American Civil War',
		date: '07.09.2025',
		map: 'novuscivilwar.png',
	},
	deadhand: {
		name: 'Dead Hand',
		date: '11.10.2025',
		map: 'deadhand.png',
	},
}
